server:
  port: 9100
  context-path: /frieza

eureka:
  instance:
    hostname: www.dragon.com
    status-page-url-path: /frieza/info
  client:
    service-url:
      defaultZone: http://www.dragon.com:9000/eureka/

spring:
  datasource:
    url: jdbc:h2:mem:frieza;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:sql/region.sql'
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  redis:
    database: 0
    host: redis.dragon.com
    port: 6379