server:
  tomcat:
    accesslog:
      enabled: true
      prefix: frieza_access_log

spring:
  application:
    name: frieza
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8

logging:
  config: classpath:logback-spring.xml
mybatis:
  config-location: classpath:mybatis-config.xml

management:
  security:
    enabled: false

info:
  app:
    name: frieza
    version: v1.0